// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: protos/finance/finance.proto

package finance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Number string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Payer  string `protobuf:"bytes,3,opt,name=payer,proto3" json:"payer,omitempty"`
	Method string `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Url    string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Amount int32  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_finance_finance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_finance_finance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_protos_finance_finance_proto_rawDescGZIP(), []int{0}
}

func (x *OrderRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrderRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *OrderRequest) GetPayer() string {
	if x != nil {
		return x.Payer
	}
	return ""
}

func (x *OrderRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *OrderRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *OrderRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type OrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alipay *Alipay `protobuf:"bytes,1,opt,name=alipay,proto3" json:"alipay,omitempty"`
	Wxpay  *Wxpay  `protobuf:"bytes,2,opt,name=wxpay,proto3" json:"wxpay,omitempty"`
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_finance_finance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_finance_finance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_protos_finance_finance_proto_rawDescGZIP(), []int{1}
}

func (x *OrderResponse) GetAlipay() *Alipay {
	if x != nil {
		return x.Alipay
	}
	return nil
}

func (x *OrderResponse) GetWxpay() *Wxpay {
	if x != nil {
		return x.Wxpay
	}
	return nil
}

type Alipay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Alipay) Reset() {
	*x = Alipay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_finance_finance_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alipay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alipay) ProtoMessage() {}

func (x *Alipay) ProtoReflect() protoreflect.Message {
	mi := &file_protos_finance_finance_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alipay.ProtoReflect.Descriptor instead.
func (*Alipay) Descriptor() ([]byte, []int) {
	return file_protos_finance_finance_proto_rawDescGZIP(), []int{2}
}

func (x *Alipay) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Wxpay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *WechatConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Pay    *WechatPay    `protobuf:"bytes,2,opt,name=pay,proto3" json:"pay,omitempty"`
}

func (x *Wxpay) Reset() {
	*x = Wxpay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_finance_finance_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wxpay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wxpay) ProtoMessage() {}

func (x *Wxpay) ProtoReflect() protoreflect.Message {
	mi := &file_protos_finance_finance_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wxpay.ProtoReflect.Descriptor instead.
func (*Wxpay) Descriptor() ([]byte, []int) {
	return file_protos_finance_finance_proto_rawDescGZIP(), []int{3}
}

func (x *Wxpay) GetConfig() *WechatConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Wxpay) GetPay() *WechatPay {
	if x != nil {
		return x.Pay
	}
	return nil
}

type WechatConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JsapiTicket string `protobuf:"bytes,1,opt,name=jsapi_ticket,json=jsapiTicket,proto3" json:"jsapi_ticket,omitempty"`
	Signature   string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	AppId       string `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	NonceStr    string `protobuf:"bytes,4,opt,name=nonce_str,json=nonceStr,proto3" json:"nonce_str,omitempty"`
}

func (x *WechatConfig) Reset() {
	*x = WechatConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_finance_finance_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WechatConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatConfig) ProtoMessage() {}

func (x *WechatConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protos_finance_finance_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatConfig.ProtoReflect.Descriptor instead.
func (*WechatConfig) Descriptor() ([]byte, []int) {
	return file_protos_finance_finance_proto_rawDescGZIP(), []int{4}
}

func (x *WechatConfig) GetJsapiTicket() string {
	if x != nil {
		return x.JsapiTicket
	}
	return ""
}

func (x *WechatConfig) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *WechatConfig) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *WechatConfig) GetNonceStr() string {
	if x != nil {
		return x.NonceStr
	}
	return ""
}

type WechatPay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp int32  `protobuf:"varint,1,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	Package   string `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	Sign      string `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	SignType  string `protobuf:"bytes,4,opt,name=sign_type,json=signType,proto3" json:"sign_type,omitempty"`
	AppId     string `protobuf:"bytes,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	NonceStr  string `protobuf:"bytes,6,opt,name=nonce_str,json=nonceStr,proto3" json:"nonce_str,omitempty"`
}

func (x *WechatPay) Reset() {
	*x = WechatPay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_finance_finance_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WechatPay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatPay) ProtoMessage() {}

func (x *WechatPay) ProtoReflect() protoreflect.Message {
	mi := &file_protos_finance_finance_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatPay.ProtoReflect.Descriptor instead.
func (*WechatPay) Descriptor() ([]byte, []int) {
	return file_protos_finance_finance_proto_rawDescGZIP(), []int{5}
}

func (x *WechatPay) GetTimeStamp() int32 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *WechatPay) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *WechatPay) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *WechatPay) GetSignType() string {
	if x != nil {
		return x.SignType
	}
	return ""
}

func (x *WechatPay) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *WechatPay) GetNonceStr() string {
	if x != nil {
		return x.NonceStr
	}
	return ""
}

var File_protos_finance_finance_proto protoreflect.FileDescriptor

var file_protos_finance_finance_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65,
	0x2f, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x92, 0x01, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x79, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x79, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5e, 0x0a, 0x0d,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a,
	0x06, 0x61, 0x6c, 0x69, 0x70, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x41, 0x6c, 0x69, 0x70, 0x61, 0x79, 0x52, 0x06,
	0x61, 0x6c, 0x69, 0x70, 0x61, 0x79, 0x12, 0x24, 0x0a, 0x05, 0x77, 0x78, 0x70, 0x61, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e,
	0x57, 0x78, 0x70, 0x61, 0x79, 0x52, 0x05, 0x77, 0x78, 0x70, 0x61, 0x79, 0x22, 0x1a, 0x0a, 0x06,
	0x41, 0x6c, 0x69, 0x70, 0x61, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x5c, 0x0a, 0x05, 0x57, 0x78, 0x70, 0x61,
	0x79, 0x12, 0x2d, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x57, 0x65, 0x63, 0x68,
	0x61, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x24, 0x0a, 0x03, 0x70, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x50, 0x61,
	0x79, 0x52, 0x03, 0x70, 0x61, 0x79, 0x22, 0x83, 0x01, 0x0a, 0x0c, 0x57, 0x65, 0x63, 0x68, 0x61,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x6a, 0x73, 0x61, 0x70, 0x69,
	0x5f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6a,
	0x73, 0x61, 0x70, 0x69, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x72, 0x22, 0xa8, 0x01, 0x0a,
	0x09, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x50, 0x61, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x69, 0x67, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f,
	0x6e, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x72, 0x32, 0x44, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x3b, 0x0a, 0x08, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x66,
	0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a,
	0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_finance_finance_proto_rawDescOnce sync.Once
	file_protos_finance_finance_proto_rawDescData = file_protos_finance_finance_proto_rawDesc
)

func file_protos_finance_finance_proto_rawDescGZIP() []byte {
	file_protos_finance_finance_proto_rawDescOnce.Do(func() {
		file_protos_finance_finance_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_finance_finance_proto_rawDescData)
	})
	return file_protos_finance_finance_proto_rawDescData
}

var file_protos_finance_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_finance_finance_proto_goTypes = []interface{}{
	(*OrderRequest)(nil),  // 0: finance.OrderRequest
	(*OrderResponse)(nil), // 1: finance.OrderResponse
	(*Alipay)(nil),        // 2: finance.Alipay
	(*Wxpay)(nil),         // 3: finance.Wxpay
	(*WechatConfig)(nil),  // 4: finance.WechatConfig
	(*WechatPay)(nil),     // 5: finance.WechatPay
}
var file_protos_finance_finance_proto_depIdxs = []int32{
	2, // 0: finance.OrderResponse.alipay:type_name -> finance.Alipay
	3, // 1: finance.OrderResponse.wxpay:type_name -> finance.Wxpay
	4, // 2: finance.Wxpay.config:type_name -> finance.WechatConfig
	5, // 3: finance.Wxpay.pay:type_name -> finance.WechatPay
	0, // 4: finance.Order.Generate:input_type -> finance.OrderRequest
	1, // 5: finance.Order.Generate:output_type -> finance.OrderResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protos_finance_finance_proto_init() }
func file_protos_finance_finance_proto_init() {
	if File_protos_finance_finance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_finance_finance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_finance_finance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_finance_finance_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alipay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_finance_finance_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wxpay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_finance_finance_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WechatConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_finance_finance_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WechatPay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_finance_finance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_finance_finance_proto_goTypes,
		DependencyIndexes: file_protos_finance_finance_proto_depIdxs,
		MessageInfos:      file_protos_finance_finance_proto_msgTypes,
	}.Build()
	File_protos_finance_finance_proto = out.File
	file_protos_finance_finance_proto_rawDesc = nil
	file_protos_finance_finance_proto_goTypes = nil
	file_protos_finance_finance_proto_depIdxs = nil
}
